import '@cadenza/components';
import '@cadenza/components/dist/styles/tokens.css';
// @ts-expect-error -- generated by @custom-elements-manifest/analyzer, not typed
import manifest from '@cadenza/components/custom-elements.json';
import axe from 'axe-core';
import './styles.css';

interface CemField {
  kind: string;
  name: string;
  privacy?: string;
  type?: { text: string };
  default?: string;
}

interface CemDeclaration {
  kind: string;
  name: string;
  description?: string;
  tagName?: string;
  customElement?: boolean;
  members?: CemField[];
}

interface CemModule {
  path: string;
  declarations: CemDeclaration[];
}

interface CemManifest {
  modules: CemModule[];
}

// The analyzer captures the TS type alias name as plain text (e.g.
// "CdzButtonType"), not its expanded union members — it doesn't resolve
// types, just reads the annotation. Rather than teach the gallery to parse
// TypeScript, known enum-like props get their options listed here once,
// per component. Anything not listed falls back to a plain text input —
// still usable, just without a dropdown.
const ENUM_HINTS: Record<string, Record<string, string[]>> = {
  'cdz-button': { type: ['button', 'submit', 'reset'] },
  'cdz-input': { type: ['text', 'email', 'password', 'tel', 'search', 'url', 'number'] }
};

// No JSDoc `@slot` annotations exist yet to read from the manifest, so
// default slotted content per tag is listed here instead.
const SLOT_CONTENT: Record<string, string> = {
  'cdz-button': 'Botón de ejemplo'
};

// Preview instances start from each field's own manifest default (mostly
// empty strings/false), which is a *valid* starting point for most props
// but not for cdz-input's required `label` — showing the gallery's own
// default preview mid-violation isn't the point, unlike deliberately
// clearing it via the control to see the warning on demand.
const DEFAULT_PROP_OVERRIDES: Record<string, Record<string, unknown>> = {
  'cdz-input': { label: 'Nombre de ejemplo' },
  'cdz-checkbox': { label: 'Acepto los términos' }
};

function parseDefault(raw: string | undefined): unknown {
  if (raw === undefined) return undefined;
  try {
    return JSON.parse(raw.replace(/'/g, '"'));
  } catch {
    return raw;
  }
}

function buildControl(tagName: string, field: CemField, target: HTMLElement): HTMLElement {
  const wrapper = document.createElement('label');
  wrapper.className = 'control';

  const labelText = document.createElement('span');
  labelText.textContent = field.name;
  wrapper.appendChild(labelText);

  // Reads the *current* value already applied to the live instance (which
  // may have been overridden via DEFAULT_PROP_OVERRIDES) rather than the
  // manifest's raw default, so the control reflects what's actually
  // rendered instead of contradicting it.
  const currentValue = (target as unknown as Record<string, unknown>)[field.name];
  const enumOptions = ENUM_HINTS[tagName]?.[field.name];

  if (enumOptions) {
    const select = document.createElement('select');
    for (const option of enumOptions) {
      const optionEl = document.createElement('option');
      optionEl.value = option;
      optionEl.textContent = option;
      select.appendChild(optionEl);
    }
    select.value = String(currentValue ?? parseDefault(field.default) ?? '');
    select.addEventListener('change', () => {
      (target as unknown as Record<string, unknown>)[field.name] = select.value;
    });
    wrapper.appendChild(select);
    return wrapper;
  }

  if (field.type?.text === 'boolean') {
    const checkbox = document.createElement('input');
    checkbox.type = 'checkbox';
    checkbox.checked = Boolean(currentValue ?? parseDefault(field.default));
    checkbox.addEventListener('change', () => {
      (target as unknown as Record<string, unknown>)[field.name] = checkbox.checked;
    });
    wrapper.appendChild(checkbox);
    return wrapper;
  }

  const text = document.createElement('input');
  text.type = 'text';
  text.value = String(currentValue ?? parseDefault(field.default) ?? '');
  text.addEventListener('input', () => {
    (target as unknown as Record<string, unknown>)[field.name] = text.value;
  });
  wrapper.appendChild(text);
  return wrapper;
}

function renderAxeResults(container: HTMLElement, results: axe.AxeResults): void {
  container.textContent = '';
  if (results.violations.length === 0) {
    const pass = document.createElement('p');
    pass.className = 'a11y-pass';
    pass.textContent = `Sin violaciones (${results.passes.length} reglas verificadas).`;
    container.appendChild(pass);
    return;
  }

  const list = document.createElement('ul');
  for (const violation of results.violations) {
    const item = document.createElement('li');
    item.className = 'a11y-violation';
    item.textContent = `[${violation.impact}] ${violation.help} (${violation.nodes.length} elemento(s))`;
    list.appendChild(item);
  }
  container.appendChild(list);
}

function buildSection(declaration: CemDeclaration): HTMLElement {
  const tagName = declaration.tagName!;
  const section = document.createElement('section');
  section.className = 'component-section';

  const heading = document.createElement('h2');
  heading.textContent = tagName;
  section.appendChild(heading);

  if (declaration.description) {
    const description = document.createElement('p');
    description.className = 'description';
    description.textContent = declaration.description;
    section.appendChild(description);
  }

  const layout = document.createElement('div');
  layout.className = 'layout';

  const preview = document.createElement('div');
  preview.className = 'preview';
  const instance = document.createElement(tagName);
  const slotContent = SLOT_CONTENT[tagName];
  if (slotContent) instance.textContent = slotContent;
  const propOverrides = DEFAULT_PROP_OVERRIDES[tagName];
  if (propOverrides) {
    Object.assign(instance, propOverrides);
  }
  preview.appendChild(instance);
  layout.appendChild(preview);

  const controlsPanel = document.createElement('div');
  controlsPanel.className = 'controls-panel';
  const publicFields = (declaration.members ?? []).filter(
    (member) => member.kind === 'field' && member.privacy !== 'private'
  );
  for (const field of publicFields) {
    controlsPanel.appendChild(buildControl(tagName, field, instance));
  }
  layout.appendChild(controlsPanel);

  section.appendChild(layout);

  const a11yPanel = document.createElement('div');
  a11yPanel.className = 'a11y-panel';
  const runButton = document.createElement('button');
  runButton.type = 'button';
  runButton.textContent = 'Verificar accesibilidad';
  const results = document.createElement('div');
  results.className = 'a11y-results';
  runButton.addEventListener('click', async () => {
    results.textContent = 'Verificando…';
    const axeResults = await axe.run(instance);
    renderAxeResults(results, axeResults);
  });
  a11yPanel.appendChild(runButton);
  a11yPanel.appendChild(results);
  section.appendChild(a11yPanel);

  return section;
}

const root = document.querySelector<HTMLDivElement>('#gallery-root')!;
const cemManifest = manifest as CemManifest;

for (const module of cemManifest.modules) {
  for (const declaration of module.declarations) {
    if (declaration.customElement && declaration.tagName) {
      root.appendChild(buildSection(declaration));
    }
  }
}
