import '@kdenza/components';
import '@kdenza/components/dist/styles/tokens.css';
// @ts-expect-error -- generated by @custom-elements-manifest/analyzer, not typed
import manifest from '@kdenza/components/custom-elements.json';
// The one place the gallery reads real source rather than the manifest:
// icon names are data in a registry, not a TypeScript union the analyzer
// could pick up, and hardcoding them here would go stale the moment an
// icon is added. See ADR-0016.
import { icons } from '@kdenza/components';
import axe from 'axe-core';
import './styles.css';

interface CemField {
  kind: string;
  name: string;
  privacy?: string;
  type?: { text: string };
  default?: string;
}

interface CemDeclaration {
  kind: string;
  name: string;
  description?: string;
  tagName?: string;
  customElement?: boolean;
  members?: CemField[];
}

interface CemModule {
  path: string;
  declarations: CemDeclaration[];
}

interface CemManifest {
  modules: CemModule[];
}

// The analyzer captures the TS type alias name as plain text (e.g.
// "CdzButtonType"), not its expanded union members — it doesn't resolve
// types, just reads the annotation. Rather than teach the gallery to parse
// TypeScript, known enum-like props get their options listed here once,
// per component. Anything not listed falls back to a plain text input —
// still usable, just without a dropdown.
const ENUM_HINTS: Record<string, Record<string, string[]>> = {
  'cdz-button': { type: ['button', 'submit', 'reset'] },
  'cdz-input': { type: ['text', 'email', 'password', 'tel', 'search', 'url', 'number'] },
  'cdz-text': {
    as: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'span'],
    size: ['heading-1', 'heading-2', 'heading-3', 'body-lg', 'body-md', 'body-sm']
  },
  'cdz-popover': { type: ['auto', 'manual'] },
  'cdz-link': { target: ['_self', '_blank'] },
  'cdz-icon': {
    // Generated from the registry, so a newly drawn icon shows up in the
    // gallery's dropdown without touching this file.
    name: Object.keys(icons),
    size: ['sm', 'md', 'lg', 'inherit']
  },
  'cdz-badge': { variant: ['neutral', 'info', 'success', 'warning', 'error'] },
  'cdz-spinner': { size: ['sm', 'md', 'lg', 'inherit'] },
  'cdz-divider': { orientation: ['horizontal', 'vertical'] },
  'cdz-avatar': { fallback: ['initials', 'icon'], size: ['sm', 'md', 'lg'] }
};

// No JSDoc `@slot` annotations exist yet to read from the manifest, so
// default slotted content per tag is listed here instead.
const SLOT_CONTENT: Record<string, string> = {
  'cdz-button': 'Botón de ejemplo',
  'cdz-text': 'Texto de ejemplo',
  'cdz-link': 'Enlace de ejemplo',
  'cdz-badge': 'Pendiente',
  // cdz-popover is a primitive, not a standalone atom -- see its own
  // gallery section for the caveat about previewing it without a real
  // anchor. This is just enough content to see the panel render at all
  // when toggled open via the `open` control.
  'cdz-popover': 'Contenido de ejemplo (sin anchor real -- ver cdz-select para el uso previsto).'
};

/**
 * Slotted content that has to be a real *element*, not text.
 *
 * `SLOT_CONTENT` assigns `textContent`, which produces a text node —
 * fine for a button's label, useless for `cdz-tooltip`, whose whole job
 * is attaching `aria-describedby` to a slotted element. A text node
 * can't carry an attribute, so the tooltip would (correctly) warn that
 * it has nothing to describe.
 */
const SLOT_ELEMENT: Record<string, () => Element> = {
  'cdz-tooltip': () => {
    const trigger = document.createElement('cdz-button');
    trigger.textContent = 'Pasa el mouse o el foco por aquí';
    return trigger;
  }
};

// Preview instances start from each field's own manifest default (mostly
// empty strings/false), which is a *valid* starting point for most props
// but not for cdz-input's required `label` — showing the gallery's own
// default preview mid-violation isn't the point, unlike deliberately
// clearing it via the control to see the warning on demand.
const DEFAULT_PROP_OVERRIDES: Record<string, Record<string, unknown>> = {
  'cdz-input': { label: 'Nombre de ejemplo' },
  'cdz-textarea': { label: 'Mensaje de ejemplo' },
  'cdz-checkbox': { label: 'Acepto los términos' },
  'cdz-radio': { label: 'Opción de ejemplo' },
  'cdz-switch': { label: 'Notificaciones' },
  'cdz-range': { label: 'Volumen' },
  'cdz-file-input': { label: 'Adjuntar CV' },
  // href is mandatory for the same reason label is on the form atoms —
  // without one, the default preview would sit permanently in its own
  // console.error state. See ADR-0015.
  'cdz-link': { href: '#ejemplo' },
  // Without a name the preview would render nothing at all.
  'cdz-icon': { name: 'check' },
  'cdz-progress': { label: 'Subiendo archivo', value: 45 },
  // Same reason as the form atoms' label: without a name there are no
  // initials and no accessible name, so the gallery would be auditing an
  // empty circle and reporting the component's own console error.
  'cdz-avatar': { name: 'Kyrah Monreal' },
  'cdz-tooltip': { text: 'Descripción de ejemplo' },
  'cdz-select': {
    label: 'País',
    options: [
      { value: 'ar', label: 'Argentina' },
      { value: 'br', label: 'Brasil' },
      { value: 'cl', label: 'Chile' }
    ]
  }
};

function parseDefault(raw: string | undefined): unknown {
  if (raw === undefined) return undefined;
  try {
    return JSON.parse(raw.replace(/'/g, '"'));
  } catch {
    return raw;
  }
}

// None of the three control types (select/checkbox/text-input) can edit
// an array meaningfully — a text input would just take a string that
// doesn't become a real array. Rather than render a control that looks
// editable but silently does nothing useful, array-typed props (e.g.
// cdz-select's `options`) get no control at all; their value still comes
// through via DEFAULT_PROP_OVERRIDES for the live preview.
function isArrayTyped(field: CemField): boolean {
  const typeText = field.type?.text ?? '';
  return typeText.includes('[]') || typeText.startsWith('Array<');
}

// Same reasoning as isArrayTyped: cdz-popover's `anchor` is genuine public
// API (a consumer component sets it programmatically), not a mistakenly-
// public internal -- so it can't just be marked `private` in the
// manifest. But a raw element reference has no meaningful generic control
// either (a text input editing it would just produce the string
// "[object HTMLElement]"), so it's excluded here instead.
function isElementRefTyped(field: CemField): boolean {
  return (field.type?.text ?? '').includes('HTMLElement');
}

function buildControl(tagName: string, field: CemField, target: HTMLElement): HTMLElement {
  const wrapper = document.createElement('label');
  wrapper.className = 'control';

  const labelText = document.createElement('span');
  labelText.textContent = field.name;
  wrapper.appendChild(labelText);

  // Reads the *current* value already applied to the live instance (which
  // may have been overridden via DEFAULT_PROP_OVERRIDES) rather than the
  // manifest's raw default, so the control reflects what's actually
  // rendered instead of contradicting it.
  const currentValue = (target as unknown as Record<string, unknown>)[field.name];
  const enumOptions = ENUM_HINTS[tagName]?.[field.name];

  if (enumOptions) {
    const select = document.createElement('select');
    // Some enum props (e.g. cdz-text's `size`) default to an empty string
    // meaning "infer from another prop," rather than always landing on one
    // of the listed options — give that state its own option so the
    // control can actually represent and return to it.
    if (currentValue === '') {
      const autoOption = document.createElement('option');
      autoOption.value = '';
      autoOption.textContent = '(auto)';
      select.appendChild(autoOption);
    }
    for (const option of enumOptions) {
      const optionEl = document.createElement('option');
      optionEl.value = option;
      optionEl.textContent = option;
      select.appendChild(optionEl);
    }
    select.value = String(currentValue ?? parseDefault(field.default) ?? '');
    select.addEventListener('change', () => {
      (target as unknown as Record<string, unknown>)[field.name] = select.value;
    });
    wrapper.appendChild(select);
    return wrapper;
  }

  if (field.type?.text === 'boolean') {
    const checkbox = document.createElement('input');
    checkbox.type = 'checkbox';
    checkbox.checked = Boolean(currentValue ?? parseDefault(field.default));
    checkbox.addEventListener('change', () => {
      (target as unknown as Record<string, unknown>)[field.name] = checkbox.checked;
    });
    wrapper.appendChild(checkbox);
    return wrapper;
  }

  // A plain text input assigns its raw string straight onto the property
  // (see below) -- fine for an actual string prop, but a real type
  // violation for a `number` one: Lit only runs the `type: Number`
  // conversion on attribute changes, not on direct property assignment,
  // so the component would end up with e.g. `value: "75"` instead of
  // `75`. cdz-range is the first component with number props central to
  // its own behavior (the fill-percent math), which is what surfaced
  // this -- same fix applies retroactively to any other number prop
  // (e.g. cdz-textarea's `rows`).
  if (field.type?.text === 'number') {
    const number = document.createElement('input');
    number.type = 'number';
    number.value = String(currentValue ?? parseDefault(field.default) ?? '');
    number.addEventListener('input', () => {
      (target as unknown as Record<string, unknown>)[field.name] = Number(number.value);
    });
    wrapper.appendChild(number);
    return wrapper;
  }

  const text = document.createElement('input');
  text.type = 'text';
  text.value = String(currentValue ?? parseDefault(field.default) ?? '');
  text.addEventListener('input', () => {
    (target as unknown as Record<string, unknown>)[field.name] = text.value;
  });
  wrapper.appendChild(text);
  return wrapper;
}

function renderAxeResults(container: HTMLElement, results: axe.AxeResults): void {
  container.textContent = '';
  if (results.violations.length === 0) {
    const pass = document.createElement('p');
    pass.className = 'a11y-pass';
    pass.textContent = `Sin violaciones (${results.passes.length} reglas verificadas).`;
    container.appendChild(pass);
    return;
  }

  const list = document.createElement('ul');
  for (const violation of results.violations) {
    const item = document.createElement('li');
    item.className = 'a11y-violation';
    item.textContent = `[${violation.impact}] ${violation.help} (${violation.nodes.length} elemento(s))`;
    list.appendChild(item);
  }
  container.appendChild(list);
}

function buildSection(declaration: CemDeclaration): HTMLElement {
  const tagName = declaration.tagName!;
  const section = document.createElement('section');
  section.className = 'component-section';

  const heading = document.createElement('h2');
  heading.textContent = tagName;
  section.appendChild(heading);

  if (declaration.description) {
    const description = document.createElement('p');
    description.className = 'description';
    description.textContent = declaration.description;
    section.appendChild(description);
  }

  const layout = document.createElement('div');
  layout.className = 'layout';

  const preview = document.createElement('div');
  preview.className = 'preview';
  const instance = document.createElement(tagName);
  const slotContent = SLOT_CONTENT[tagName];
  if (slotContent) instance.textContent = slotContent;
  const slotElement = SLOT_ELEMENT[tagName];
  if (slotElement) instance.appendChild(slotElement());
  const propOverrides = DEFAULT_PROP_OVERRIDES[tagName];
  if (propOverrides) {
    Object.assign(instance, propOverrides);
  }
  preview.appendChild(instance);
  layout.appendChild(preview);

  const controlsPanel = document.createElement('div');
  controlsPanel.className = 'controls-panel';
  const publicFields = (declaration.members ?? []).filter(
    (member) =>
      member.kind === 'field' &&
      member.privacy !== 'private' &&
      !isArrayTyped(member) &&
      !isElementRefTyped(member)
  );
  for (const field of publicFields) {
    controlsPanel.appendChild(buildControl(tagName, field, instance));
  }
  layout.appendChild(controlsPanel);

  section.appendChild(layout);

  const a11yPanel = document.createElement('div');
  a11yPanel.className = 'a11y-panel';
  const runButton = document.createElement('button');
  runButton.type = 'button';
  runButton.textContent = 'Verificar accesibilidad';
  const results = document.createElement('div');
  results.className = 'a11y-results';
  runButton.addEventListener('click', async () => {
    results.textContent = 'Verificando…';
    const axeResults = await axe.run(instance);
    renderAxeResults(results, axeResults);
  });
  a11yPanel.appendChild(runButton);
  a11yPanel.appendChild(results);
  section.appendChild(a11yPanel);

  return section;
}

/**
 * A contact sheet of the whole icon set, rendered large and side by side.
 *
 * Not a nicety: normalising the first three icons (ADR-0016) turned up an
 * optical-weight problem that was flatly invisible at their real 16px
 * size and obvious the moment they were lined up at 96px. That audit was
 * done with a throwaway overlay injected into the page; this is the same
 * view, kept, so drawing the next icon doesn't need one.
 *
 * The `.live-area` box is the 20×20 rule drawn on top — remembering that
 * it bounds the *stroked* extent, not the path geometry.
 */
function buildIconContactSheet(): HTMLElement {
  const section = document.createElement('section');
  section.className = 'component-section';

  const heading = document.createElement('h2');
  heading.textContent = 'Set de íconos';
  section.appendChild(heading);

  const description = document.createElement('p');
  description.className = 'description';
  description.textContent =
    'Todos los íconos del registro a 96px, con el área viva de 20×20 superpuesta. ' +
    'Sirve para juzgar peso óptico entre íconos — a tamaño real no se ve. ' +
    'Se genera desde shared/icons.ts, así que un ícono nuevo aparece solo.';
  section.appendChild(description);

  const sheet = document.createElement('div');
  sheet.className = 'icon-sheet';

  for (const name of Object.keys(icons)) {
    const cell = document.createElement('figure');
    cell.className = 'icon-cell';

    const frame = document.createElement('div');
    frame.className = 'icon-frame';
    // The live-area guide sits behind a real <cdz-icon>, so what's being
    // judged is the shipping component, not a re-drawn copy of it.
    frame.innerHTML = '<span class="live-area" aria-hidden="true"></span>';
    const icon = document.createElement('cdz-icon');
    icon.setAttribute('name', name);
    icon.setAttribute('size', 'lg');
    frame.appendChild(icon);

    const caption = document.createElement('figcaption');
    caption.textContent = name;

    cell.appendChild(frame);
    cell.appendChild(caption);
    sheet.appendChild(cell);
  }

  section.appendChild(sheet);
  return section;
}

const root = document.querySelector<HTMLDivElement>('#gallery-root')!;
const cemManifest = manifest as CemManifest;

for (const module of cemManifest.modules) {
  for (const declaration of module.declarations) {
    if (declaration.customElement && declaration.tagName) {
      root.appendChild(buildSection(declaration));
      if (declaration.tagName === 'cdz-icon') {
        root.appendChild(buildIconContactSheet());
      }
    }
  }
}
